"""Professional Mode visual-asset contracts.

The package is intentionally additive and inert until an explicit Professional
Mode binding is created. Standard Mode does not import or consult it.
"""

from .binding import bind_professional_mode, select_reference_views
from .authority import (
    AssetChannelClaim,
    ReferenceAdmissionDecision,
    ReferenceAdmissionResolver,
    ReferenceAdmissionResult,
    ReferenceChannelEvidence,
    ReferenceChannelPlan,
    ReferenceEvidencePacket,
    VisualAssetBindingSet,
)
from .anchor_pack import (
    AnchorCandidateAttempt,
    AnchorCandidateResult,
    AnchorGenerationRequest,
    AnchorPackPreparationRequest,
    AnchorPackPreparationResult,
    AnchorPackPreparationService,
    AnchorReviewDecision,
)
from .character_card import (
    BODY_SOURCE_CLASSES,
    BODY_SLOT_KEYS,
    EXPRESSION_SLOT_KEYS,
    FACE_SLOT_KEYS,
    BodyPreparationRequest,
    CharacterCardCandidateAttempt,
    CharacterCardCandidateRequest,
    CharacterCardCandidateResult,
    CharacterCardPreparationService,
    CharacterCardStageHost,
    CharacterCardSlot,
    CharacterCardStageResult,
    CharacterCardState,
    ExpressionPreparationRequest,
)
from .catalog import InMemoryVisualAssetCatalog, PersistentVisualAssetCatalog, PeopleAssetRevision
from .runtime_bridge import CanonicalProviderPromptReceipt, ProfessionalModeRuntimeBridge
from .lifecycle import (
    AnchorPackPreparationHost,
    PeopleAssetActivationRequest,
    PeopleAssetCreateRequest,
    PeopleAssetLifecycleService,
    PeopleAssetPrepareRequest,
)
from .library import (
    FrozenVisualAssetBindingSet,
    LibraryAssetPreparationHost,
    LibraryRootSourceProvenance,
    LibraryVisualAssetCreateRequest,
    PersistentProjectVisualAssetBindingService,
    PersistentVisualAssetLibraryCatalog,
    ProjectVisualAssetBinding,
    ProjectVisualAssetBindingRequest,
    ProjectVisualAssetBindingService,
    ProjectVisualAssetBindingSet,
    VisualAsset,
    VisualAssetLibraryCatalog,
    VisualAssetLibraryLifecycleService,
    VisualAssetVersion,
)
from .execution import (
    ProfessionalModeExecutionContext,
    ProfessionalModeExecutionRequest,
    ProfessionalModeExecutionAdapter,
    ProfessionalModePreparationResult,
)
from .consumers import (
    ProfessionalConsumerContext,
    ProfessionalConsumerRequest,
    ProfessionalModeConsumerAdapter,
)
from .contracts import (
    AnchorView,
    FaceIdentityModule,
    IdentityAnchorPackVersion,
    IdentityScoreSummary,
    PeopleAsset,
    ProfessionalModeBinding,
    RootSourceProvenance,
)

__all__ = [
    "AnchorView",
    "AnchorCandidateAttempt",
    "AnchorCandidateResult",
    "AnchorGenerationRequest",
    "AnchorPackPreparationRequest",
    "AnchorPackPreparationResult",
    "AnchorPackPreparationService",
    "AnchorReviewDecision",
    "BODY_SOURCE_CLASSES",
    "BODY_SLOT_KEYS",
    "EXPRESSION_SLOT_KEYS",
    "FACE_SLOT_KEYS",
    "BodyPreparationRequest",
    "CharacterCardCandidateAttempt",
    "CharacterCardCandidateRequest",
    "CharacterCardCandidateResult",
    "CharacterCardPreparationService",
    "CharacterCardStageHost",
    "CharacterCardSlot",
    "CharacterCardStageResult",
    "CharacterCardState",
    "ExpressionPreparationRequest",
    "AssetChannelClaim",
    "FaceIdentityModule",
    "IdentityAnchorPackVersion",
    "IdentityScoreSummary",
    "PeopleAsset",
    "ProfessionalModeBinding",
    "RootSourceProvenance",
    "InMemoryVisualAssetCatalog",
    "PersistentVisualAssetCatalog",
    "PeopleAssetRevision",
    "CanonicalProviderPromptReceipt",
    "ReferenceAdmissionDecision",
    "ReferenceAdmissionResolver",
    "ReferenceAdmissionResult",
    "ReferenceChannelEvidence",
    "ReferenceChannelPlan",
    "ReferenceEvidencePacket",
    "VisualAssetBindingSet",
    "ProfessionalModeRuntimeBridge",
    "PeopleAssetActivationRequest",
    "PeopleAssetCreateRequest",
    "PeopleAssetLifecycleService",
    "PeopleAssetPrepareRequest",
    "AnchorPackPreparationHost",
    "FrozenVisualAssetBindingSet",
    "LibraryAssetPreparationHost",
    "LibraryRootSourceProvenance",
    "LibraryVisualAssetCreateRequest",
    "PersistentProjectVisualAssetBindingService",
    "PersistentVisualAssetLibraryCatalog",
    "ProjectVisualAssetBinding",
    "ProjectVisualAssetBindingRequest",
    "ProjectVisualAssetBindingService",
    "ProjectVisualAssetBindingSet",
    "VisualAsset",
    "VisualAssetLibraryCatalog",
    "VisualAssetLibraryLifecycleService",
    "VisualAssetVersion",
    "ProfessionalModeExecutionAdapter",
    "ProfessionalModeExecutionContext",
    "ProfessionalModeExecutionRequest",
    "ProfessionalModePreparationResult",
    "ProfessionalConsumerContext",
    "ProfessionalConsumerRequest",
    "ProfessionalModeConsumerAdapter",
    "bind_professional_mode",
    "select_reference_views",
]
