"""V3-owned shared capability layer."""

from .base import SharedCapabilityModule
from .asset_binding_planner import AssetBindingPlanner
from .asset_role_analyzer import AssetRoleAnalyzer
from .case_library import CaseLibraryRetriever
from .contracts import (
    AssetRole,
    CapabilityConstraint,
    CapabilityInput,
    CapabilityResult,
    CapabilityRunResult,
    CapabilityRunStatus,
    CapabilityStatus,
    CapabilityTargetStage,
    CapabilityWarning,
    UploadedAssetInfo,
)
from .history_reference import HistoryReferenceModule
from .information_integrity import InformationIntegrityLockModule
from .output_review import OutputReviewModule
from .prompt_constraint_compiler import PromptConstraintCompiler
from .registry import SharedCapabilityRegistry
from .visual_cluster import (
    AntiAIFaceReviewResult,
    AutoRetryDecision,
    CommercialQualityClosureReviewer,
    CommercialQualityIssue,
    CommercialOutputSelection,
    GeneratedOutputResolution,
    HumanPhotorealismGuidance,
    HumanPhotorealismLayer,
    IdentityHeroSelectionPlan,
    ModeQualityProfile,
    ModeQualityProfileBuilder,
    OpenAIVisionInspectionProvider,
    PostGenerationReviewPackage,
    OutputQualityReviewMerger,
    RealReviewCandidateSignal,
    RealReviewSignalPackage,
    STRONG_REFERENCE_CLOSURE_MODULE_ID,
    MODE_QUALITY_PROFILE_MODULE_ID,
    VISUAL_CAPABILITY_CLUSTER_ID,
    VISUAL_CLUSTER_CHILD_MODULE_IDS,
    ProjectVisualGrammarSnapshot,
    StrongReferenceBinding,
    StrongReferenceClosureBuilder,
    StrongReferenceClosurePackage,
    StrictVisualReviewPolicy,
    VisualCapabilityClusterModule,
    VisualCapabilityClusterResult,
    VisualCommercialQualityReview,
    VisualConsistencyGuardResult,
    VisualGrammarProfile,
    VisualIdentityLockProfile,
    VisualInspectionReport,
    VisionOutputInspector,
    VisionInspectionProviderError,
    VisionInspectionProviderUnavailable,
    VisualQualityReviewReport,
    VisualQualityReviewResult,
    VisualReferenceBindingProfile,
    create_default_vision_provider,
)
from .visual_grammar_lock import VisualGrammarLockModule

__all__ = [
    "AssetRole",
    "AssetBindingPlanner",
    "AssetRoleAnalyzer",
    "CaseLibraryRetriever",
    "CapabilityConstraint",
    "CapabilityInput",
    "CapabilityResult",
    "CapabilityRunResult",
    "CapabilityRunStatus",
    "CapabilityStatus",
    "CapabilityTargetStage",
    "CapabilityWarning",
    "AntiAIFaceReviewResult",
    "AutoRetryDecision",
    "CommercialQualityClosureReviewer",
    "CommercialQualityIssue",
    "CommercialOutputSelection",
    "GeneratedOutputResolution",
    "HumanPhotorealismGuidance",
    "HumanPhotorealismLayer",
    "IdentityHeroSelectionPlan",
    "MODE_QUALITY_PROFILE_MODULE_ID",
    "ModeQualityProfile",
    "ModeQualityProfileBuilder",
    "HistoryReferenceModule",
    "InformationIntegrityLockModule",
    "OpenAIVisionInspectionProvider",
    "OutputReviewModule",
    "OutputQualityReviewMerger",
    "PostGenerationReviewPackage",
    "RealReviewCandidateSignal",
    "RealReviewSignalPackage",
    "PromptConstraintCompiler",
    "SharedCapabilityModule",
    "SharedCapabilityRegistry",
    "UploadedAssetInfo",
    "VISUAL_CAPABILITY_CLUSTER_ID",
    "VISUAL_CLUSTER_CHILD_MODULE_IDS",
    "ProjectVisualGrammarSnapshot",
    "STRONG_REFERENCE_CLOSURE_MODULE_ID",
    "StrongReferenceBinding",
    "StrongReferenceClosureBuilder",
    "StrongReferenceClosurePackage",
    "StrictVisualReviewPolicy",
    "VisualCapabilityClusterModule",
    "VisualCapabilityClusterResult",
    "VisualCommercialQualityReview",
    "VisualConsistencyGuardResult",
    "VisualGrammarProfile",
    "VisualIdentityLockProfile",
    "VisualInspectionReport",
    "VisionOutputInspector",
    "VisionInspectionProviderError",
    "VisionInspectionProviderUnavailable",
    "VisualQualityReviewReport",
    "VisualQualityReviewResult",
    "VisualReferenceBindingProfile",
    "VisualGrammarLockModule",
    "create_default_vision_provider",
]
