"""V3-owned product API boundary."""

from .contracts import (
    AssetSeriesItem,
    BrandApiResponse,
    CampaignRequest,
    CampaignSummary,
    CandidateSummary,
    CreateBrandRequest,
    CreateCreativeJobRequest,
    EcommerceCapabilitySummary,
    GenerateJobRequest,
    GeneralCreativeCapabilitySummary,
    ProductJobStatus,
    ProductJobStatusValue,
    ScenarioSummary,
    SelectResultRequest,
    SelectionResponse,
    SelectedResult,
    StyleContinuationSummary,
    V3AssetContentUploadRequest,
    V3AssetUploadCreateRequest,
    V3AssetUploadStatusValue,
    V3ExportDownloadPayload,
    V3ExportPackageResponse,
    V3UploadedAssetRecord,
)
from .lifecycle import (
    CandidateRecord,
    CandidateSelectionRecord,
    ExportRecord,
    JobLifecycleRecord,
    JobRecord,
    RevisionRecord,
    RunRecord,
)
from .service import V3ProductApi, V3ProductApiService, create_default_product_api
from .assets import V3UploadedAssetStore
from .outputs import V3GeneratedOutputRecord, V3GeneratedOutputStore

__all__ = [
    "AssetSeriesItem",
    "BrandApiResponse",
    "CandidateRecord",
    "CampaignRequest",
    "CampaignSummary",
    "CandidateSummary",
    "CandidateSelectionRecord",
    "CreateBrandRequest",
    "CreateCreativeJobRequest",
    "EcommerceCapabilitySummary",
    "ExportRecord",
    "GenerateJobRequest",
    "GeneralCreativeCapabilitySummary",
    "JobLifecycleRecord",
    "JobRecord",
    "ProductJobStatus",
    "ProductJobStatusValue",
    "RevisionRecord",
    "RunRecord",
    "ScenarioSummary",
    "SelectResultRequest",
    "SelectedResult",
    "SelectionResponse",
    "StyleContinuationSummary",
    "V3AssetContentUploadRequest",
    "V3AssetUploadCreateRequest",
    "V3AssetUploadStatusValue",
    "V3ExportDownloadPayload",
    "V3ExportPackageResponse",
    "V3GeneratedOutputRecord",
    "V3GeneratedOutputStore",
    "V3ProductApi",
    "V3ProductApiService",
    "V3UploadedAssetRecord",
    "V3UploadedAssetStore",
    "create_default_product_api",
]
