"""V3-native visual capability cluster."""

from .contracts import (
    AdaptiveReferenceSelectionPlan,
    AntiAIFaceReviewResult,
    AutoRetryDecision,
    BatchIdentityDiversityReview,
    BeautifulRealismBalanceReview,
    BoneStructureRetryPatch,
    CommercialQualityIssue,
    CommercialOutputSelection,
    GeneratedOutputResolution,
    GeneralSuiteRole,
    GeneralSuiteRolePlan,
    HumanBatchDiversityReview,
    HumanIdentityAnchorProfile,
    HumanNaturalVariationPlan,
    HumanPhotorealismGuidance,
    IdentityHeroSelectionPlan,
    IdentityDriftGuardPlan,
    IdentityMetricResult,
    IdentityRepairStrategyPlan,
    IdentityReviewFusion,
    ModeQualityProfile,
    ModeDifferentiationReview,
    ModeExecutionPolicy,
    ModeRoleRecipe,
    PostGenerationReviewPackage,
    PortraitBoneStructureLock,
    PortraitReferenceBalancePolicy,
    PortraitReferenceBalanceRetryPatch,
    PortraitReferenceBalanceReview,
    PortraitIdentityStyleSeparationReview,
    PortraitIdentitySimilarityReview,
    PortraitReferenceInfluencePolicy,
    PromptOwnershipDecision,
    ProjectIdentityAnchor,
    ReferenceChannelPolicy,
    ReferenceOverinheritanceRetryPatch,
    RealReviewCandidateSignal,
    RealReviewSignalPackage,
    RoleSpecificGenerationPlan,
    ResolvedReferencePolicyPackage,
    StrongReferenceBinding,
    StrongReferenceClosurePackage,
    StrongReferenceContinuationPlan,
    StrictVisualReviewPolicy,
    StylingDeltaPolicy,
    SubjectIdentityCard,
    SubjectContinuityAssetPackage,
    SubjectContinuityEvidence,
    VisualCapabilityClusterResult,
    VisualCommercialQualityReview,
    VisualConsistencyGuardResult,
    VisualGrammarProfile,
    VisualIdentityLockProfile,
    VisualInspectionReport,
    VisualQualityReviewReport,
    VisualQualityReviewResult,
    VisualReferenceBindingProfile,
    ProjectVisualGrammarSnapshot,
)
from .adaptive_reference import ADAPTIVE_REFERENCE_RETRIEVER_MODULE_ID, AdaptiveReferenceRetriever
from .batch_identity_review import BatchIdentityDiversityReviewer
from .casebook_recipes import (
    VISUAL_CASEBOOK_RECIPE_LIBRARY_ID,
    VISUAL_HUMAN_ATTRACTIVE_REALISM_BALANCE_ID,
    VISUAL_HUMAN_EAST_ASIAN_FAIR_COMPLEXION_GUARD_ID,
    VISUAL_HUMAN_REAL_CAMERA_TUNING_ID,
    VISUAL_PROMPT_ATOM_RECIPE_ID,
    apply_role_recipe_casebook_overlay,
    human_photorealism_casebook,
    prompt_atom_recipe,
    provider_casebook_prompt_lines,
    strong_reference_casebook_rules,
)
from .commercial_quality import CommercialQualityClosureReviewer
from .doc66_closure import (
    MODE_QUALITY_PROFILE_MODULE_ID,
    STRONG_REFERENCE_CLOSURE_MODULE_ID,
    ModeQualityProfileBuilder,
    StrongReferenceClosureBuilder,
)
from .expression_review import (
    AffectiveExpressionReviewReceipt,
    EXPRESSION_FRAMING_DELTA_MAX,
    EXPRESSION_REVIEW_BLOCKING_ISSUE_CODES,
    LAUGH_EXPRESSION_EVIDENCE_CODES,
    LAUGH_EXPRESSION_SLOT_REQUIRED_EVIDENCE_CODES,
    laugh_expression_receipt_allows_slot,
    normalize_affective_expression_score_card,
    project_laugh_expression_review_receipt,
)
from .general_suite_director import GeneralSuiteDirector
from .human_photorealism import HumanPhotorealismLayer
from .identity_anchor import ProjectIdentityAnchorBuilder
from .identity_drift_guard import IDENTITY_DRIFT_GUARD_MODULE_ID, IdentityDriftGuard
from .identity_metric import SFaceIdentityMetricProvider, create_default_identity_metric_provider
from .identity_repair_strategy import IDENTITY_REPAIR_STRATEGY_MODULE_ID, IdentityRepairStrategyRouter
from .module import VISUAL_CAPABILITY_CLUSTER_ID, VISUAL_CLUSTER_CHILD_MODULE_IDS, VisualCapabilityClusterModule
from .human_variation import HumanNaturalVariationPolicy
from .mode_role_director import ModeAwareRoleDirector
from .portrait_identity import (
    DOC86_IDENTITY_ISSUE_CODES,
    DOC87_REFERENCE_BOUNDARY_ISSUE_CODES,
    DOC88_REFERENCE_BALANCE_ISSUE_CODES,
    PortraitBoneStructureIdentityLayer,
)
from .reference_channel_policy import (
    REFERENCE_CHANNEL_ISSUE_CODES,
    REFERENCE_CHANNEL_POLICY_MODULE_ID,
    PromptOwnershipResolver,
    ReferenceChannelPolicyModule,
    reference_channel_retry_patch,
)
from .quality_review import OutputQualityReviewMerger
from .strong_reference_loop import StrongReferenceLoopPlanner
from .subject_asset_memory import SUBJECT_CONTINUITY_ASSET_PACK_MODULE_ID, SubjectContinuityAssetPackBuilder
from .vision_inspector import VisionOutputInspector
from .vision_provider import (
    OpenAIVisionInspectionProvider,
    VisionInspectionProviderError,
    VisionInspectionProviderUnavailable,
    create_default_vision_provider,
)

__all__ = [
    "ADAPTIVE_REFERENCE_RETRIEVER_MODULE_ID",
    "AdaptiveReferenceRetriever",
    "AdaptiveReferenceSelectionPlan",
    "AffectiveExpressionReviewReceipt",
    "AntiAIFaceReviewResult",
    "AutoRetryDecision",
    "BatchIdentityDiversityReview",
    "BatchIdentityDiversityReviewer",
    "BeautifulRealismBalanceReview",
    "BoneStructureRetryPatch",
    "CommercialQualityIssue",
    "CommercialQualityClosureReviewer",
    "CommercialOutputSelection",
    "GeneratedOutputResolution",
    "GeneralSuiteDirector",
    "GeneralSuiteRole",
    "GeneralSuiteRolePlan",
    "HumanBatchDiversityReview",
    "HumanIdentityAnchorProfile",
    "HumanNaturalVariationPlan",
    "HumanNaturalVariationPolicy",
    "HumanPhotorealismGuidance",
    "HumanPhotorealismLayer",
    "IdentityHeroSelectionPlan",
    "IDENTITY_DRIFT_GUARD_MODULE_ID",
    "IdentityDriftGuard",
    "IdentityDriftGuardPlan",
    "IdentityMetricResult",
    "IDENTITY_REPAIR_STRATEGY_MODULE_ID",
    "IdentityRepairStrategyPlan",
    "IdentityRepairStrategyRouter",
    "IdentityReviewFusion",
    "LAUGH_EXPRESSION_EVIDENCE_CODES",
    "LAUGH_EXPRESSION_SLOT_REQUIRED_EVIDENCE_CODES",
    "VISUAL_CASEBOOK_RECIPE_LIBRARY_ID",
    "VISUAL_HUMAN_ATTRACTIVE_REALISM_BALANCE_ID",
    "VISUAL_HUMAN_EAST_ASIAN_FAIR_COMPLEXION_GUARD_ID",
    "VISUAL_HUMAN_REAL_CAMERA_TUNING_ID",
    "VISUAL_PROMPT_ATOM_RECIPE_ID",
    "MODE_QUALITY_PROFILE_MODULE_ID",
    "ModeQualityProfile",
    "ModeQualityProfileBuilder",
    "ModeAwareRoleDirector",
    "ModeDifferentiationReview",
    "ModeExecutionPolicy",
    "ModeRoleRecipe",
    "OutputQualityReviewMerger",
    "OpenAIVisionInspectionProvider",
    "PostGenerationReviewPackage",
    "PortraitBoneStructureIdentityLayer",
    "PortraitBoneStructureLock",
    "PortraitReferenceBalancePolicy",
    "PortraitReferenceBalanceRetryPatch",
    "PortraitReferenceBalanceReview",
    "PortraitIdentityStyleSeparationReview",
    "PortraitIdentitySimilarityReview",
    "PortraitReferenceInfluencePolicy",
    "PromptOwnershipDecision",
    "PromptOwnershipResolver",
    "ProjectIdentityAnchor",
    "ProjectIdentityAnchorBuilder",
    "SFaceIdentityMetricProvider",
    "ProjectVisualGrammarSnapshot",
    "project_laugh_expression_review_receipt",
    "REFERENCE_CHANNEL_ISSUE_CODES",
    "REFERENCE_CHANNEL_POLICY_MODULE_ID",
    "ReferenceChannelPolicy",
    "ReferenceChannelPolicyModule",
    "reference_channel_retry_patch",
    "laugh_expression_receipt_allows_slot",
    "normalize_affective_expression_score_card",
    "ReferenceOverinheritanceRetryPatch",
    "apply_role_recipe_casebook_overlay",
    "human_photorealism_casebook",
    "prompt_atom_recipe",
    "provider_casebook_prompt_lines",
    "strong_reference_casebook_rules",
    "RealReviewCandidateSignal",
    "RealReviewSignalPackage",
    "RoleSpecificGenerationPlan",
    "ResolvedReferencePolicyPackage",
    "STRONG_REFERENCE_CLOSURE_MODULE_ID",
    "StrongReferenceBinding",
    "StrongReferenceClosureBuilder",
    "StrongReferenceClosurePackage",
    "StrongReferenceContinuationPlan",
    "StrongReferenceLoopPlanner",
    "StrictVisualReviewPolicy",
    "StylingDeltaPolicy",
    "SubjectIdentityCard",
    "SUBJECT_CONTINUITY_ASSET_PACK_MODULE_ID",
    "SubjectContinuityAssetPackBuilder",
    "SubjectContinuityAssetPackage",
    "SubjectContinuityEvidence",
    "DOC86_IDENTITY_ISSUE_CODES",
    "DOC87_REFERENCE_BOUNDARY_ISSUE_CODES",
    "DOC88_REFERENCE_BALANCE_ISSUE_CODES",
    "EXPRESSION_FRAMING_DELTA_MAX",
    "EXPRESSION_REVIEW_BLOCKING_ISSUE_CODES",
    "VISUAL_CAPABILITY_CLUSTER_ID",
    "VISUAL_CLUSTER_CHILD_MODULE_IDS",
    "VisualCapabilityClusterModule",
    "VisualCapabilityClusterResult",
    "VisualCommercialQualityReview",
    "VisualConsistencyGuardResult",
    "VisualGrammarProfile",
    "VisualIdentityLockProfile",
    "VisualInspectionReport",
    "VisionOutputInspector",
    "VisionInspectionProviderError",
    "VisionInspectionProviderUnavailable",
    "VisualQualityReviewReport",
    "VisualQualityReviewResult",
    "VisualReferenceBindingProfile",
    "create_default_vision_provider",
    "create_default_identity_metric_provider",
]
