"""V3-native visual capability cluster."""

from .contracts import (
    AntiAIFaceReviewResult,
    AutoRetryDecision,
    BatchIdentityDiversityReview,
    BeautifulRealismBalanceReview,
    BoneStructureRetryPatch,
    CommercialQualityIssue,
    CommercialOutputSelection,
    GeneratedOutputResolution,
    GeneralSuiteRole,
    GeneralSuiteRolePlan,
    HumanBatchDiversityReview,
    HumanIdentityAnchorProfile,
    HumanNaturalVariationPlan,
    HumanPhotorealismGuidance,
    IdentityHeroSelectionPlan,
    ModeQualityProfile,
    ModeDifferentiationReview,
    ModeExecutionPolicy,
    ModeRoleRecipe,
    PostGenerationReviewPackage,
    PortraitBoneStructureLock,
    PortraitIdentityStyleSeparationReview,
    PortraitIdentitySimilarityReview,
    PortraitReferenceInfluencePolicy,
    ProjectIdentityAnchor,
    ReferenceOverinheritanceRetryPatch,
    RealReviewCandidateSignal,
    RealReviewSignalPackage,
    RoleSpecificGenerationPlan,
    StrongReferenceBinding,
    StrongReferenceClosurePackage,
    StrongReferenceContinuationPlan,
    StrictVisualReviewPolicy,
    StylingDeltaPolicy,
    SubjectIdentityCard,
    VisualCapabilityClusterResult,
    VisualCommercialQualityReview,
    VisualConsistencyGuardResult,
    VisualGrammarProfile,
    VisualIdentityLockProfile,
    VisualInspectionReport,
    VisualQualityReviewReport,
    VisualQualityReviewResult,
    VisualReferenceBindingProfile,
    ProjectVisualGrammarSnapshot,
)
from .batch_identity_review import BatchIdentityDiversityReviewer
from .casebook_recipes import (
    VISUAL_CASEBOOK_RECIPE_LIBRARY_ID,
    VISUAL_HUMAN_ATTRACTIVE_REALISM_BALANCE_ID,
    VISUAL_HUMAN_EAST_ASIAN_FAIR_COMPLEXION_GUARD_ID,
    VISUAL_HUMAN_REAL_CAMERA_TUNING_ID,
    VISUAL_PROMPT_ATOM_RECIPE_ID,
    apply_role_recipe_casebook_overlay,
    human_photorealism_casebook,
    prompt_atom_recipe,
    provider_casebook_prompt_lines,
    strong_reference_casebook_rules,
)
from .commercial_quality import CommercialQualityClosureReviewer
from .doc66_closure import (
    MODE_QUALITY_PROFILE_MODULE_ID,
    STRONG_REFERENCE_CLOSURE_MODULE_ID,
    ModeQualityProfileBuilder,
    StrongReferenceClosureBuilder,
)
from .general_suite_director import GeneralSuiteDirector
from .human_photorealism import HumanPhotorealismLayer
from .identity_anchor import ProjectIdentityAnchorBuilder
from .module import VISUAL_CAPABILITY_CLUSTER_ID, VISUAL_CLUSTER_CHILD_MODULE_IDS, VisualCapabilityClusterModule
from .human_variation import HumanNaturalVariationPolicy
from .mode_role_director import ModeAwareRoleDirector
from .portrait_identity import (
    DOC86_IDENTITY_ISSUE_CODES,
    DOC87_REFERENCE_BOUNDARY_ISSUE_CODES,
    PortraitBoneStructureIdentityLayer,
)
from .quality_review import OutputQualityReviewMerger
from .strong_reference_loop import StrongReferenceLoopPlanner
from .vision_inspector import VisionOutputInspector
from .vision_provider import (
    OpenAIVisionInspectionProvider,
    VisionInspectionProviderError,
    VisionInspectionProviderUnavailable,
    create_default_vision_provider,
)

__all__ = [
    "AntiAIFaceReviewResult",
    "AutoRetryDecision",
    "BatchIdentityDiversityReview",
    "BatchIdentityDiversityReviewer",
    "BeautifulRealismBalanceReview",
    "BoneStructureRetryPatch",
    "CommercialQualityIssue",
    "CommercialQualityClosureReviewer",
    "CommercialOutputSelection",
    "GeneratedOutputResolution",
    "GeneralSuiteDirector",
    "GeneralSuiteRole",
    "GeneralSuiteRolePlan",
    "HumanBatchDiversityReview",
    "HumanIdentityAnchorProfile",
    "HumanNaturalVariationPlan",
    "HumanNaturalVariationPolicy",
    "HumanPhotorealismGuidance",
    "HumanPhotorealismLayer",
    "IdentityHeroSelectionPlan",
    "VISUAL_CASEBOOK_RECIPE_LIBRARY_ID",
    "VISUAL_HUMAN_ATTRACTIVE_REALISM_BALANCE_ID",
    "VISUAL_HUMAN_EAST_ASIAN_FAIR_COMPLEXION_GUARD_ID",
    "VISUAL_HUMAN_REAL_CAMERA_TUNING_ID",
    "VISUAL_PROMPT_ATOM_RECIPE_ID",
    "MODE_QUALITY_PROFILE_MODULE_ID",
    "ModeQualityProfile",
    "ModeQualityProfileBuilder",
    "ModeAwareRoleDirector",
    "ModeDifferentiationReview",
    "ModeExecutionPolicy",
    "ModeRoleRecipe",
    "OutputQualityReviewMerger",
    "OpenAIVisionInspectionProvider",
    "PostGenerationReviewPackage",
    "PortraitBoneStructureIdentityLayer",
    "PortraitBoneStructureLock",
    "PortraitIdentityStyleSeparationReview",
    "PortraitIdentitySimilarityReview",
    "PortraitReferenceInfluencePolicy",
    "ProjectIdentityAnchor",
    "ProjectIdentityAnchorBuilder",
    "ProjectVisualGrammarSnapshot",
    "ReferenceOverinheritanceRetryPatch",
    "apply_role_recipe_casebook_overlay",
    "human_photorealism_casebook",
    "prompt_atom_recipe",
    "provider_casebook_prompt_lines",
    "strong_reference_casebook_rules",
    "RealReviewCandidateSignal",
    "RealReviewSignalPackage",
    "RoleSpecificGenerationPlan",
    "STRONG_REFERENCE_CLOSURE_MODULE_ID",
    "StrongReferenceBinding",
    "StrongReferenceClosureBuilder",
    "StrongReferenceClosurePackage",
    "StrongReferenceContinuationPlan",
    "StrongReferenceLoopPlanner",
    "StrictVisualReviewPolicy",
    "StylingDeltaPolicy",
    "SubjectIdentityCard",
    "DOC86_IDENTITY_ISSUE_CODES",
    "DOC87_REFERENCE_BOUNDARY_ISSUE_CODES",
    "VISUAL_CAPABILITY_CLUSTER_ID",
    "VISUAL_CLUSTER_CHILD_MODULE_IDS",
    "VisualCapabilityClusterModule",
    "VisualCapabilityClusterResult",
    "VisualCommercialQualityReview",
    "VisualConsistencyGuardResult",
    "VisualGrammarProfile",
    "VisualIdentityLockProfile",
    "VisualInspectionReport",
    "VisionOutputInspector",
    "VisionInspectionProviderError",
    "VisionInspectionProviderUnavailable",
    "VisualQualityReviewReport",
    "VisualQualityReviewResult",
    "VisualReferenceBindingProfile",
    "create_default_vision_provider",
]
